### ISSUE TITLE
所有的nagram 11.0都无法使用

### ISSUE THREAD

**Issue by Dystnine** [LiuYi0526/Nagram#10]
**Describe the bug**
打开白屏卡死
**To Reproduce**
1. 下载
2. 安装
3. 打开

**Logcat**
Settings - click version - "Enable Log", then click "Send Logs" to [@NekoXChat](https://t.me/NekoXChat) or just upload at issue.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. MI6]MI6
 - OS: [e.g. Android8.1]Android 13
 - Version [e.g. 5.15.0]11.0

**Additional context**

**Comment by LiuYi0526** [comment]
已去除genuine
